### ISSUE TITLE
Missing template processor

### ISSUE THREAD

**Issue by papricek** [kennethkalmer/ember-cli-nouislider#2]
When installing last version (0.3.0), when running "ember server", I get the following:

```
Missing template processor
Error: Missing template processor
    at module.exports.preprocessTemplates (/Users/patrikjira/www/goferrata/goferrata/node_modules/ember-cli/lib/preprocessors.js:149:11)
    at Class.Addon.compileTemplates (/Users/patrikjira/www/goferrata/goferrata/node_modules/ember-cli/lib/models/addon.js:434:12)
    at Class.Addon.compileAddon (/Users/patrikjira/www/goferrata/goferrata/node_modules/ember-cli/lib/models/addon.js:456:28)
    at Class.Addon.treeForAddon (/Users/patrikjira/www/goferrata/goferrata/node_modules/ember-cli/lib/models/addon.js:382:24)
    at Class._treeFor (/Users/patrikjira/www/goferrata/goferrata/node_modules/ember-cli/lib/models/addon.js:282:31)
    at Class.treeFor (/Users/patrikjira/www/goferrata/goferrata/node_modules/ember-cli/lib/models/addon.js:253:19)
    at EmberApp.<anonymous> (/Users/patrikjira/www/goferrata/goferrata/node_modules/ember-cli/lib/broccoli/ember-app.js:307:20)
    at Array.map (native)
    at EmberApp.addonTreesFor (/Users/patrikjira/www/goferrata/goferrata/node_modules/ember-cli/lib/broccoli/ember-app.js:305:30)
    at EmberApp._addonTree (/Users/patrikjira/www/goferrata/goferrata/node_modules/ember-cli/lib/broccoli/ember-app.js:597:38)
```

Any ideas?

**Comment by papricek** [comment]
resolved by ember-cli upgrade! ;)

**Comment by kennethkalmer** [comment]
Glad you won, and thanks for using ember-cli-nouislider!
